version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: academico
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - db

  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - keycloak

  frontend:
    build: ../frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
